### ISSUE TITLE
Decentraland Template

### ISSUE THREAD

**Issue by lkngtn** [aragonone/product#170]
# Idea
## User story
We would like to create a organization template for help Decentraland deploy an organization for managing the LAND contract. 

Related issues: [1](#)

## Technical requirements
See comment bellow with YAML configuration file for the template.

**Comment by lkngtn** [comment]
YAML configuration for template creation for Decentraland Phase 1:

There are two variables that are relevant:

`$MANA_TOKEN_ADDRESS` = `0x28BcE5263f5d7F4EB7e8C6d5d78275CA455BAc63` (on rinkeby)
`$DCLMulti` = `0x0de35b8b47b129877e0efca24e294b61d7e7eee3` (on rinkeby)

The intention is to create the initial phase for testing, where the Mana token can be wrapped using the token-wrapper app to generate a Minime Voting token, and can be used to vote on proposal. The only type of proposal that is relevant will be transactions via the Agent app. 

Both the Wrapped-Mana-Voting app and the DCLMultisig directly will be able to execute actions on behalf of the Agent.

``` 
---
id: decentraland-phase1
apps:
- ref: mana-wrapper
  type: token-wrapper
  token: $MANA_TOKEN_ADDRESS
- ref: mana-voting
  type: voting
  token: mana-wrapper
  support: 50
  acceptance: 5
  duration: 604800
- ref: agent
  type: agent
  default: true
actions:
permissions:
- app: kernel
  role: APP_MANAGER_ROLE
  grantee: $DCLMulti
  manager: $DCLMulti
- app: acl
  role: CREATE_PERMISSIONS_ROLE
  grantee: $DCLMulti
  manager: $DCLMulti
- app: mana-voting
  role: CREATE_VOTES_ROLE
  grantee: mana-wrapper
  manager: $DCLMulti
- app: mana-voting
  role: MODIFY_QUORUM_ROLE
  grantee: mana-voting
  manager: $DCLMulti
- app: mana-voting
  role: MODIFY_SUPPORT_ROLE
  grantee: mana-voting
  manager: $DCLMulti
- app: agent
  role: EXECUTE_ROLE
  grantee: mana-voting
  manager: $DCLMulti
- app: agent
  role: EXECUTE_ROLE
  grantee: $DCLMulti
  manager: $DCLMulti
- app: agent
  role: RUN_SCRIPT_ROLE
  grantee: mana-voting
  manager: $DCLMulti
- app: agent
  role: RUN_SCRIPT_ROLE
  grantee: $DCLMulti
  manager: $DCLMulti
- app: agent
  role: TRANSFER_ROLE
  grantee: $DCLMulti
  manager: $DCLMulti
```
