### ISSUE TITLE
Nest Org Template

### ISSUE THREAD

**Issue by lkngtn** [aragonone/product#171]
# Idea
## User story
As as user, I want *x, y and z*.

Related issues: [1](#)

## Technical requirements
To let the user perform *x, y and z*, we need to implement *a, b and c*. Those require to implement *d, e and f*.

**Comment by lkngtn** [comment]
Here is the YAML config file for the proposed nest org:

There is a variable $AA_ACCOUNT which we will need to adjust before deployment.

```
---
id: nest
tokens:
- ref: member
  symbol: Member
  name: Member Token
  transferable: false
  decimals: 0
apps:
- ref: member-voting
  type: voting
  token: member
  support: 66
  acceptance: 50
  duration: 1296000
- ref: member-tm
  type: token-manager
  token: member
- type: finance
  default: true
  vault: vault
  period: 2592000
- ref: vault
  type: vault
  default: true
- ref: approvals
  type: approvals
actions:
- ref: mint-members
  name: MintTokens
  params:
  - token: member
    amounts: "$MEMBER_AMOUNTS"
    to: "$MEMBER_KEYS"
permissions:
- app: kernel
  role: APP_MANAGER_ROLE
  grantee: $AA_ACCOUNT
  manager: $AA_ACCOUNT
- app: acl
  role: CREATE_PERMISSIONS_ROLE
  grantee: $AA_ACCOUNT
  manager: $AA_ACCOUNT
- app: member-voting
  role: CREATE_VOTES_ROLE
  grantee: member-tm
  manager: $AA_ACCOUNT
- app: member-voting
  role: MODIFY_QUORUM_ROLE
  grantee: member-voting
  manager: $AA_ACCOUNT
- app: member-voting
  role: MODIFY_SUPPORT_ROLE
  grantee: member-voting
  manager: $AA_ACCOUNT
- app: vault
  role: TRANSFER_ROLE
  grantee: finance
  manager: $AA_ACCOUNT
- app: finance
  role: CREATE_PAYMENTS_ROLE
  grantee: member-voting
  manager: $AA_ACCOUNT
- app: finance
  role: EXECUTE_PAYMENTS_ROLE
  grantee: member-voting
  manager: $AA_ACCOUNT
- app: finance
  role: MANAGE_PAYMENTS_ROLE
  grantee: member-voting
  manager: $AA_ACCOUNT
- app: member-tm
  role: BURN_ROLE
  grantee: member-voting
  manager: $AA_ACCOUNT
- app: member-tm
  role: BURN_ROLE
  grantee: $AA_ACCOUNT
- app: member-tm
  role: MINT_ROLE
  grantee: member-voting
  manager: $AA_ACCOUNT
- app: member-tm
  role: MINT_ROLE
  grantee: $AA_ACCOUNT
- app: approvals
  role: SUBMIT_ROLE
  grantee: ANY
  manager: $AA_ACCOUNT
- app: approvals
  role: APPROVE_ROLE
  grantee: $AA_ACCOUNT
  manager: $AA_ACCOUNT
- app: approvals
  role: REJECT_ROLE
  grantee: $AA_ACCOUNT
  manager: $AA_ACCOUNT
```
