### ISSUE TITLE
Yaml Config to Template Readme Converter

### ISSUE THREAD

**Issue by lkngtn** [aragonone/product#172]
# Idea
## User story

In order to streamline and specify template creation in a consistent fashion we have been aligning around a yaml configuration format. Example of the company template:

Note: this file doesn't account for variables in the config, but that won't be relevant for outputting the permissions. 

``` 
---
id: company
tokens:
- ref: share
  symbol: Share
  name: Share Token
  decimals: 18
apps:
- ref: shareholder-voting
  type: voting
  token: share
  support: 50
  acceptance: 5
  duration: 604800
- ref: share-tm
  type: token-manager
  token: share
- type: finance
  default: true
  vault: agent
  period: 2592000
- ref: agent
  type: agent
  default: true
actions:
- ref: mint-shares
  name: MintTokens
  params:
  - token: share
    amounts: "$SHARE_AMOUNTS"
    to: "$SHARE_KEYS"
permissions:
- app: kernel
  role: APP_MANAGER_ROLE
  grantee: share-voting
  manager: share-voting
- app: acl
  role: CREATE_PERMISSIONS_ROLE
  grantee: share-voting
  manager: share-voting
- app: share-voting
  role: CREATE_VOTES_ROLE
  grantee: share-tm
  manager: share-voting
- app: share-voting
  role: MODIFY_QUORUM_ROLE
  grantee: share-voting
  manager: share-voting
- app: share-voting
  role: MODIFY_SUPPORT_ROLE
  grantee: share-voting
  manager: share-voting
- app: agent
  role: EXECUTE_ROLE
  grantee: share-voting
  manager: share-voting
- app: agent
  role: RUN_SCRIPT_ROLE
  grantee: share-voting
  manager: share-voting
- app: agent
  role: TRANSFER_ROLE
  grantee: finance
  manager: share-voting
- app: finance
  role: CREATE_PAYMENTS_ROLE
  grantee: share-voting
  manager: share-voting
- app: finance
  role: EXECUTE_PAYMENTS_ROLE
  grantee: share-voting
  manager: share-voting
- app: finance
  role: MANAGE_PAYMENTS_ROLE
  grantee: share-voting
  manager: share-voting
- app: share-tm
  role: BURN_ROLE
  grantee: share-voting
  manager: share-voting
- app: share-tm
  role: MINT_ROLE
  grantee: share-voting
  manager: share-voting
```

Eventually we want to be able to use these to do better automated deployments, export configurations from other daos, but initially it would be helpful to simply test the format and simplify readme creation by creating a permissions table using the yaml file as a template. 

Related issues: https://github.com/aragon/dao-templates/pull/130

## Technical requirements
see related issue
